### ISSUE TITLE
Alt teksten

### ISSUE THREAD

**Issue by SamaraFellaDina** [aliceafanasieva/the-startup-responsive-interactieve-website#1]
voor de `alt` elementen in de afbeeldingen zou ik een andere benaming gebruiken. Ik zou dan ook geen "-" ertussen doen, aangezien dit voor toegankelijheid misschien vervelend kan zijn

**Comment by aliceafanasieva** [comment]
Ik heb alle altelementen een andere benaming gegeven, zoals ik in een artikel heb gelezen over hoe je een mooie alt attribuut maakt. [3ebed62](https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/commit/3ebed6277f2e97f24b695b5e42dfe26771ad48cc)
