### ISSUE TITLE
disc i.p.v. een svg

### ISSUE THREAD

**Issue by SamaraFellaDina** [aliceafanasieva/the-startup-responsive-interactieve-website#3]
![image](https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/assets/144009778/db0a7917-4f0e-4d8f-ae03-1686f89e6f1f)

Je kan voor deze lijst misschien beter `list-style-decoration: disc;` gebruiken en dit element dan blauw maken, dan heb je er misschien meer controle over en dan kan je het verticaal beter centreren misschien

https://www.w3schools.com/cssref/pr_list-style-type.php

**Comment by aliceafanasieva** [comment]
Ik heb aanpassingen gedaan aan de bullets, nu zijn ze wel gecentreerd. 
[cbc99ab](https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/commit/cbc99aba3d20877469fa7b41dc76b9b7c434a04a)
