### ISSUE TITLE
Duplicate gebruik van ID

### ISSUE THREAD

**Issue by latoyaln** [aliceafanasieva/the-startup-responsive-interactieve-website#7]
https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/blob/5330d51e1a3ee88b95a6f79350ef891e374c56cf/index.html#L73

https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/blob/5330d51e1a3ee88b95a6f79350ef891e374c56cf/index.html#L116

Je gebruikt 2 keer het id modal. Bij lijn 73 en lijn 116. Een ID moet uniek zijn. Je kan dit oplossen door 1 van de 2 van ID te veranderen.

Lees meer op: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by aliceafanasieva** [comment]
Ik heb de issue opgelost door tweede id te veranderen [0c0deb4](https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/commit/0c0deb4a2a4b372527740ff70cba906705ff1e8a)
