### ISSUE TITLE
script in javascript file

### ISSUE THREAD

**Issue by Seijno** [aliceafanasieva/the-startup-responsive-interactieve-website#8]
op het moment heb je alle script in de index staan. Ik zou het lekker in een script file zetten en het verbinden met je index, dat is een stuk overzichtelijker

bron: [What are some key benefits of including a JavaScript file in HTML?](https://www.quora.com/What-are-some-key-benefits-of-including-a-JavaScript-file-in-HTML)

**Comment by aliceafanasieva** [comment]
Bedankt! Issue opgelost door naar aparte js bestand te verwijzen in html script. 
[bb389e8](https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/commit/bb389e8b33c4807e707f3dd9e002c7a530934c7d)
