### ISSUE TITLE
Required Field nog niet compleet.

### ISSUE THREAD

**Issue by TygoWolven** [aliceafanasieva/the-startup-responsive-interactieve-website#9]
Toen ik je interactie aan het bekijken was, zag ik dat er een 'Full Name' als 'required' stond voor je form. Voor een voor- en achternaam. Nu vulde ik alleen mijn voornaam in en was de 'required' al voldoende en kon ik door naar de volgende stap. Ik denk dat dit niet helemaal klopt, aangezien dit niet mijn volledige naam is.

Om dit op te lossen kun je 2 input-fields maken, één voor je voornaam, en één voor je achternaam en die allebei 'required' maken. Of je moet een manier vinden waarop je in je 'required' kan zeggen dat er minimaal 2 woorden in moeten staan. Ik denk dat het het makkelijkste is als je het op een van deze 2 manieren maakt.

//

<img width="400" src="https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/assets/144010858/f30d7369-b7b5-46ed-bbf0-e963bd0a1e20">

<br> 

<img width="400" src="https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/assets/144010858/63f880ab-b803-48a5-903f-1245ccc20371">

**Comment by aliceafanasieva** [comment]
Thanks! Door ipv full name twee aparte variabelen first en last name te maken, wordt het apart gechecked op de invul en wordt het ervoor gezorgd dat alle gegevens door de user zijn ingevuld.
[b129033](https://github.com/aliceafanasieva/the-startup-responsive-interactieve-website/commit/b129033b69b861561178ed84c1ac1bb9891d3688)
